// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'BuildingCard': typeof import("../components/BuildingCard.vue")['default'],
    'BuildingsTable': typeof import("../components/BuildingsTable.vue")['default'],
    'BuildingTable': typeof import("../components/BuildingTable.vue")['default'],
    'LoginForm': typeof import("../components/LoginForm.vue")['default'],
    'Search': typeof import("../components/Search.vue")['default'],
    'TheSideBar': typeof import("../components/TheSideBar.vue")['default'],
    'GEDRecursiveComponent': typeof import("../components/GED/RecursiveComponent.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
    'LazyBuildingCard': typeof import("../components/BuildingCard.vue")['default'],
    'LazyBuildingsTable': typeof import("../components/BuildingsTable.vue")['default'],
    'LazyBuildingTable': typeof import("../components/BuildingTable.vue")['default'],
    'LazyLoginForm': typeof import("../components/LoginForm.vue")['default'],
    'LazySearch': typeof import("../components/Search.vue")['default'],
    'LazyTheSideBar': typeof import("../components/TheSideBar.vue")['default'],
    'LazyGEDRecursiveComponent': typeof import("../components/GED/RecursiveComponent.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export const BuildingCard: typeof import("../components/BuildingCard.vue")['default']
export const BuildingsTable: typeof import("../components/BuildingsTable.vue")['default']
export const BuildingTable: typeof import("../components/BuildingTable.vue")['default']
export const LoginForm: typeof import("../components/LoginForm.vue")['default']
export const Search: typeof import("../components/Search.vue")['default']
export const TheSideBar: typeof import("../components/TheSideBar.vue")['default']
export const GEDRecursiveComponent: typeof import("../components/GED/RecursiveComponent.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const NuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const LazyBuildingCard: typeof import("../components/BuildingCard.vue")['default']
export const LazyBuildingsTable: typeof import("../components/BuildingsTable.vue")['default']
export const LazyBuildingTable: typeof import("../components/BuildingTable.vue")['default']
export const LazyLoginForm: typeof import("../components/LoginForm.vue")['default']
export const LazySearch: typeof import("../components/Search.vue")['default']
export const LazyTheSideBar: typeof import("../components/TheSideBar.vue")['default']
export const LazyGEDRecursiveComponent: typeof import("../components/GED/RecursiveComponent.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
